2021-09-30 14:46:15,258 ERROR [root] [testhttp.py (test_wm:48] - eval() arg 1 must be a string, bytes or code object
2021-09-30 14:46:15,259 ERROR [root] [http_request.py (http_request:32] - 请求方式错误
2021-09-30 14:46:15,259 ERROR [root] [testhttp.py (test_wm:48] - 'str' object has no attribute 'items'
2021-09-30 14:46:15,259 ERROR [root] [testhttp.py (test_wm:48] - eval() arg 1 must be a string, bytes or code object
2021-09-30 14:46:15,260 ERROR [root] [testhttp.py (test_wm:48] - eval() arg 1 must be a string, bytes or code object
2021-09-30 14:46:15,274 ERROR [root] [testhttp.py (test_wm:48] - eval() arg 1 must be a string, bytes or code object
2021-09-30 14:46:19,368 ERROR [root] [http_request.py (http_request:32] - 请求方式错误
2021-09-30 14:46:19,369 ERROR [root] [testhttp.py (test_wm:48] - HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /pinter/bank/api/login2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000175A3B1C5C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2021-09-30 14:53:41,039 ERROR [root] [http_request.py (http_request:32] - 请求方式错误
2021-09-30 14:53:41,040 ERROR [root] [testhttp.py (test001:51] - HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /pinter/bank/api/login2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016753956B08>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2021-09-30 14:53:45,128 ERROR [root] [http_request.py (http_request:32] - 请求方式错误
2021-09-30 14:53:45,128 ERROR [root] [testhttp.py (test001:51] - HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /pinter/bank/api/query2?userName=admin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001675395B2C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2021-09-30 14:58:00,215 ERROR [root] [http_request.py (http_request:32] - 请求方式错误
2021-09-30 14:58:00,216 ERROR [root] [testhttp.py (test001:34] - HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /pinter/bank/api/login2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000184B6207848>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2021-09-30 14:58:04,315 ERROR [root] [http_request.py (http_request:32] - 请求方式错误
2021-09-30 14:58:04,316 ERROR [root] [testhttp.py (test001:34] - HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /pinter/bank/api/query2?userName=admin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000184B620B9C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2021-09-30 15:00:03,071 ERROR [root] [http_request.py (http_request:32] - 请求方式错误
2021-09-30 15:00:03,072 ERROR [root] [testhttp.py (test001:50] - HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /pinter/bank/api/login2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B169975448>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2021-09-30 15:00:07,137 ERROR [root] [http_request.py (http_request:32] - 请求方式错误
2021-09-30 15:00:07,138 ERROR [root] [testhttp.py (test001:50] - HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /pinter/bank/api/query2?userName=admin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B169979948>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2021-09-30 15:01:07,332 ERROR [root] [http_request.py (http_request:32] - 请求方式错误
2021-09-30 15:01:07,333 ERROR [root] [testhttp.py (test001:50] - HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /pinter/bank/api/login2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027A2F2D77C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2021-09-30 15:01:11,422 ERROR [root] [http_request.py (http_request:32] - 请求方式错误
2021-09-30 15:01:11,422 ERROR [root] [testhttp.py (test001:50] - HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /pinter/bank/api/query2?userName=admin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027A2F2DB108>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2021-09-30 15:01:18,775 ERROR [root] [http_request.py (http_request:32] - 请求方式错误
2021-09-30 15:01:18,776 ERROR [root] [testhttp.py (test001:49] - HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /pinter/bank/api/login2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C42BBE7988>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2021-09-30 15:01:22,860 ERROR [root] [http_request.py (http_request:32] - 请求方式错误
2021-09-30 15:01:22,860 ERROR [root] [testhttp.py (test001:49] - HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /pinter/bank/api/query2?userName=admin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C42BBEBAC8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2021-09-30 15:01:44,548 ERROR [root] [http_request.py (http_request:32] - 请求方式错误
2021-09-30 15:01:44,549 ERROR [root] [testhttp.py (test001:48] - HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /pinter/bank/api/login2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F0E5C36E08>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2021-09-30 15:01:48,628 ERROR [root] [http_request.py (http_request:32] - 请求方式错误
2021-09-30 15:01:48,629 ERROR [root] [testhttp.py (test001:48] - HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /pinter/bank/api/query2?userName=admin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F0E5C5AD08>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2021-09-30 15:06:37,383 ERROR [root] [http_request.py (http_request:32] - 请求方式错误
2021-09-30 15:06:37,383 ERROR [root] [testhttp.py (test001:47] - HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /pinter/bank/api/login2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001902FCA7AC8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2021-09-30 15:06:41,482 ERROR [root] [http_request.py (http_request:32] - 请求方式错误
2021-09-30 15:06:41,483 ERROR [root] [testhttp.py (test001:47] - HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /pinter/bank/api/query2?userName=admin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001902FCAB2C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2021-09-30 15:11:24,286 ERROR [root] [http_request.py (http_request:32] - 请求方式错误
2021-09-30 15:11:24,287 ERROR [root] [testhttp.py (test001:37] - HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /pinter/bank/api/login2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015565F975C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2021-09-30 15:11:28,374 ERROR [root] [http_request.py (http_request:32] - 请求方式错误
2021-09-30 15:11:28,375 ERROR [root] [testhttp.py (test001:37] - HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /pinter/bank/api/query2?userName=admin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015565F9A448>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2021-09-30 15:12:17,977 ERROR [root] [http_request.py (http_request:32] - 请求方式错误
2021-09-30 15:12:17,978 ERROR [root] [testhttp.py (test001:33] - HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /pinter/bank/api/login2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FD28167848>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2021-09-30 15:12:22,049 ERROR [root] [http_request.py (http_request:32] - 请求方式错误
2021-09-30 15:12:22,049 ERROR [root] [testhttp.py (test001:33] - HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /pinter/bank/api/query2?userName=admin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FD2816BA48>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2021-09-30 15:12:42,438 ERROR [root] [http_request.py (http_request:32] - 请求方式错误
2021-09-30 15:12:42,439 ERROR [root] [testhttp.py (test001:33] - HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /pinter/bank/api/login2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BBF0FD7B48>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2021-09-30 15:12:57,976 ERROR [root] [http_request.py (http_request:32] - 请求方式错误
